## Numpy

In [2]:
import numpy as np

In [21]:
a = np.array([1,2,3], dtype='int32')
a

array([1, 2, 3])

In [6]:
b = np.array([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [7]:
# Get Dimension
a.ndim

1

In [8]:
b.ndim

2

In [9]:
a.shape

(3,)

In [10]:
b.shape

(2, 3)

In [15]:
# Get Type
a.dtype

dtype('int16')

In [13]:
b.dtype

dtype('float64')

In [22]:
#Get Size
a.itemsize

4

In [17]:
b.itemsize

8

In [23]:
a.size

3

In [24]:
a.size * a.itemsize

12

In [25]:
a.nbytes

12

In [26]:
c = np.array([[1,2,3,4,5,6,7], [8, 9, 10, 11, 12, 13, 14]])
print(c)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [28]:
# Get a specific element [r, c]
c[1,5]

13

In [30]:
# Get a specific row
c[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [31]:
# Get a specific column
c[:, 2]

array([ 3, 10])

In [34]:
# get a range within the row or column [start index, end index, stepsize]
c[0, 1:6:2]


array([2, 4, 6])

In [36]:
c[0, 1:-1: 2]

array([2, 4, 6])

In [38]:
# changing elements
c[1,5] = 20
print(c)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [39]:
c[:, 2] = 5
print(c)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


In [41]:
c[:, 3] = [0, 9]
print(c)

[[ 1  2  5  0  5  6  7]
 [ 8  9  5  9 12 20 14]]


### 3D examples

In [43]:
d = np.array([[[1,2], [3,4]],[[5, 6], [7,8]]])
print(d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [46]:
# Get Specific alement (work outside in)
d[0,1,1]

4

In [52]:
d[:,1,:]

array([[3, 4],
       [7, 8]])

In [55]:
# Replacing elements
d[:,1,:] = [[9,9], [8,8]]
d

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

## Intializing matrices

In [56]:
# All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [57]:
# All ones
np.ones((4, 2, 2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [59]:
# Any other number
np.full((2,2), 99, dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [60]:
# Any other number with (full_like)
np.full_like(c, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [62]:
# Random decimal numbers
np.random.rand(4,2, 3)

array([[[0.84663213, 0.73575877, 0.66596567],
        [0.3757425 , 0.08572714, 0.37311579]],

       [[0.89509572, 0.01393089, 0.41127252],
        [0.19012855, 0.9052966 , 0.05397977]],

       [[0.90608422, 0.04814548, 0.15420149],
        [0.8248168 , 0.52138614, 0.36342994]],

       [[0.88414012, 0.24123776, 0.79535229],
        [0.51600305, 0.31741934, 0.23344922]]])

In [70]:
# Random integer numbers
np.random.randint(-4,8, size=(3, 3))

array([[-1,  4,  0],
       [-4,  0,  0],
       [ 4, -3, -2]])

In [73]:
# The Identity Matrix (square matrix by nature)
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [75]:
# Repeat an Array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [84]:
output = np.ones((5,5))
z = np.zeros((3,3))
print(output)
print(z)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [104]:
output[1:4,1:4] = z

In [105]:
output

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [110]:
output[2,2] = 9

In [111]:
output

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

### Be careful when copying arrays!

In [117]:
a1 = np.array([1,2,3])
b1 = a1
a1

array([1, 2, 3])

In [118]:
b1[0] = 100
b1

array([100,   2,   3])

In [119]:
a1

array([100,   2,   3])

In [120]:
a1[0] = 1

In [121]:
# use the copy() method
b2 = a1.copy()
b2

array([1, 2, 3])

## Mathematics

In [122]:
m = np.array([1, 2, 3, 4])
print(m)

[1 2 3 4]


In [126]:
m + 2

array([3, 4, 5, 6])

In [127]:
m - 3

array([-2, -1,  0,  1])

In [128]:
m * 4

array([ 4,  8, 12, 16])

In [129]:
m / 2

array([0.5, 1. , 1.5, 2. ])

In [130]:
m **2

array([ 1,  4,  9, 16], dtype=int32)

In [132]:
m += 2
m

array([5, 6, 7, 8])

In [133]:
n = np.array([1,0,1,0])
m + n

array([6, 6, 8, 8])

In [134]:
np.sin(m)

array([-0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825])

In [137]:
np.cos(m)

array([ 0.28366219,  0.96017029,  0.75390225, -0.14550003])

In [138]:
np.tan(m)

array([-3.38051501, -0.29100619,  0.87144798, -6.79971146])

In [139]:
np.log(m)

array([1.60943791, 1.79175947, 1.94591015, 2.07944154])

## Linear Algebra

In [140]:
la = np.ones((2,3))
print(la)

lb = np.full((3,2), 2)
print(lb)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [143]:
np.matmul(la, lb)

array([[6., 6.],
       [6., 6.]])

## Statistics

In [144]:
stats = np.array([[1,2,3], [4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [145]:
np.min(stats)

1

In [147]:
np.max(stats, axis = 1)

array([3, 6])

In [148]:
np.sum(stats)

21

In [149]:
np.median(stats)

3.5

## Rearranging Arrays

In [152]:
before = np.array([[1,2,3,4], [5,6,7,8]])
print(before)

after = before.reshape(8,1)
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [154]:
## Vertically Stacking Matrics
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
np.vstack([v1,v2,v1,v2,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [157]:
# Horizontal Stacks
h1 = np.ones((2,4))
h2 = np.zeros((2,2))
np.hstack((h1,h2,h2,h1))

array([[1., 1., 1., 1., 0., 0., 0., 0., 1., 1., 1., 1.],
       [1., 1., 1., 1., 0., 0., 0., 0., 1., 1., 1., 1.]])